// ============================================================
//  SPDA SELECTED STUDENTS — SHARED DATA FILE
//  Sirf yahan data add/edit karein.
//  Dono pages (main site + selected-students) automatically
//  yahi data use karenge.
//
//  Photo add karne ka tarika:
//    photo: "rahul.jpg"   ← image file same folder mein honi chahiye
//    photo: null          ← emoji show hoga
// ============================================================

const ALL_STUDENTS = [
  { name: "Yogendar", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/yogendar.png", icon: "🎖️" },
  { name: "Meenu", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/meenu.jpg", icon: "🎖️" },
  { name: "Anushka", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/anushka.jpg", icon: "🎖️" },
  { name: "Bhavana Pushkar", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Bhavana Pushkar.jpg", icon: "🎖️" },
  { name: "Gaurav", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Gaurav.jpg", icon: "🎖️" },
  { name: "Chandrapratap", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Chandrapratap.jpg", icon: "🎖️" },
  { name: "Suraj yadav", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Suraj yadav.png", icon: "🎖️" },
  { name: "Sumit", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Sumit.jpg", icon: "🎖️" },
  { name: "Ankit", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Ankit.jpg", icon: "🎖️" },
  { name: "Ruchi", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Ruchi.jpg", icon: "🎖️" },
  { name: "Pradeep", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Pradeep.jpg", icon: "🎖️" },
  { name: "Sachin", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Sachin.jpg", icon: "🎖️" },
  { name: "Kashyap", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Kashyap.jpg", icon: "🎖️" },
  { name: "Geeta", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Geeta.jpg", icon: "🎖️" },
  { name: "Kaushal", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Kaushal.jpg", icon: "🎖️" },
  { name: "Preeti", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Preeti.jpg", icon: "🎖️" },
  { name: "Aman", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Aman.jpg", icon: "🎖️" },
  { name: "Swati", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Swati.png", icon: "🎖️" },
  { name: "Jitendra", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Jitendra.jpg", icon: "🎖️" },
  { name: "Gopal Singham", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Gopal Singham.jpg", icon: "🎖️" },
  { name: "Jhelum", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Jhelum.jpg", icon: "🎖️" },
  { name: "Harinder", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Harinder.jpg", icon: "🎖️" },
  { name: "Sapna", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Sapna.jpg", icon: "🎖️" },
  { name: "Sunny", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Sunny.png", icon: "🎖️" },
  { name: "Sakshi", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Sakshi.jpg", icon: "🎖️" },
  { name: "Honey", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Honey.jpg", icon: "🎖️" },
  { name: "Deepti", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Deepti.jpg", icon: "🎖️" },
  { name: "Suman", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Suman.jpg", icon: "🎖️" },
  { name: "Richa", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Richa.jpg", icon: "🎖️" },
  { name: "Neelam", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Neelam.jpg", icon: "🎖️" },
  { name: "Priyanka", village: null,      district: "Hathras, UP",       post: "UP police",    year: "2026", photo: "batch1/Priyanka.jpg", icon: "🎖️" },
  { name: "Shani", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Shani.jpg", icon: "🎖️" },
  { name: "Pushpender", village: null,      district: "Aligarh, UP",       post: "UP police",    year: "2026", photo: "batch1/Pushpender.jpg", icon: "🎖️" },
  { name: "Soni", village: null,      district: "Kasganj, UP",       post: "UP police",    year: "2026", photo: "batch1/Soni.jpg", icon: "🎖️" },
  { name: "Harjeet", village: null,      district: "Phaphund, UP",       post: "UP police",    year: "2026", photo: "batch1/Harjeet.png", icon: "🎖️" },
  { name: "Kareena", village: null,      district: "Firozabad, UP",       post: "UP police",    year: "2026", photo: "batch1/Kareena.jpg", icon: "🎖️" },
  { name: "Mohit", village: null,      district: "Aligarh, UP",       post: "UP police",    year: "2026", photo: "batch1/Mohit.jpg", icon: "🎖️" },
  { name: "Manveer", village: null,      district: "Kasganj, UP",       post: "UP police",    year: "2026", photo: "batch1/Manveer.jpg", icon: "🎖️" },
  { name: "Kahmir", village: "Etah",      district: "Shikohabad, UP",       post: "UP police",    year: "2026", photo: "batch1/Kahmir.jpg", icon: "🎖️" },
  { name: "Atul Yadav", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Atul yadav.jpg", icon: "🎖️" },
  { name: "Saurav", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Saurav.jpg", icon: "🎖️" },
  { name: "Yamini", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Yamini.jpg", icon: "🎖️" },
  { name: "Sonu", village: null,      district: "Kasganj, UP",       post: "UP police",    year: "2026", photo: "batch1/Sonu.jpg", icon: "🎖️" },
  { name: "Kumari Anshu", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Kumari Anshu.jpg", icon: "🎖️" },
  { name: "Shivam", village: null,      district: "Aligarh, UP",       post: "UP police",    year: "2026", photo: "batch1/Shivam.jpg", icon: "🎖️" },
  { name: "Ankit Nagla", village: "Nagla",      district: "UP",       post: "UP police",    year: "2026", photo: "batch1/Ankit Nagla.png", icon: "🎖️" },
  { name: "Sandeep", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/Sandeep.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.png", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.png", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.png", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
  { name: "", village: "Etah",      district: "Etah, UP",       post: "UP police",    year: "2026", photo: "batch1/.jpg", icon: "🎖️" },
];
